#!/bin/bash
# Script Name:   var assignment builtins
# Author: jcbrent
# Created Date: 7 April 2018
# Modified by: < append to the Modified by list for ehlp reference if needed.>
# Modified Date(s):
# Style Guide: This script is written to conform to the Google Bash Script Style
#              Guide available at:  https://google.github.io/styleguide/shell.xml
# PURPOSE:
# Script to add new users to the system, for help desk personnel with Admin priviledges (root access).
# ------------------------------------------------------------------------------------


# HELP_DESK_ID_GLOBAL=$(id -u)

 HELP_DESK_ID_GLOBAL=${UID}


echo ${HELP_DESK_ID_GLOBAL}


 HELP_DESK_ID_GLOBAL2="${UID}"

echo "UID_VALUE="${UID}"  # This is the preferred way."
echo "${HELP_DESK_ID_GLOBAL2}"


 Assignment:
 -----------
 Can assign the results of a command: such as hostname.
 SERVER_NAME=$(hostname)   OR older way has back-ticks: SERVER_NAME=$`hostname`
 > must have parenthesis around the command.

Expression evaluation
----------------------

for server in $(cat servers)

> the $ parenthesis means to evaluate or expand the out put the of the expression
inside the ().
